endpoint: wss://prod-kusama-collator-01.mangatafinance.cloud
mock-signature-host: true
block: ${env.MANGATA_BLOCK_NUMBER}
db: ./mangata.db.sqlite
port: 9946

registered-types:
    types:
      ShufflingSeed:
        seed: 'H256'
        proof: 'H512'
      Header:
        parentHash: 'Hash'
        number: 'Compact<BlockNumber>'
        stateRoot: 'Hash'
        extrinsicsRoot: 'Hash'
        digest: 'Digest'
        seed: 'ShufflingSeed'
        count: 'BlockNumber'

import-storage:
  Sudo:
    Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  Tokens:
    Accounts:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
          - token: 0
        - free: '1000000000000000000000000' # 1M MG
      -
        -
          - 5EekB3dsQ4yW6WukZRL5muXb4qKvJMpJdXW3w59SptYHBkvk
          - token: 0
        - free: '1000000000000000000000000' # 1M MG
      -
        -
          - 5EekB3dsQ4yW6WukZRL5muXb4qKvJMpJdXW3w59SptYHBkvk
          - token: 30
        - free: '1000000000' # 1K USDT
      -
        -
          - 5EekB3dsQ4yW6WukZRL5muXb4qKvJMpJdXW3w59SptYHBkvk
          - token: 4
        - free: '1000000000000000' # 1K KSM
  Council:
    Members: [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]
